### ISSUE TITLE
Switch to using Handle everywhere we interact with Workers

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#1848]
[Handle](https://github.com/ockam-network/ockam/tree/ockam_v0.27.0/implementations/rust/ockam/ockam_entity/src/lib.rs#L41) should be moved to ockam_node and used everywhere we interact with Workers in request-response manner (e.g. VaultSync)

**Comment by Hraesvel** [comment]
I've been working on this for a bit. [hraesvel/tranpose_handle](https://github.com/ockam-network/ockam/compare/develop...Hraesvel:hraesvel/transpose_handle?expand=1) some of the highlights are listed below.

- I've moved Handle into `ockam_node::handle` bacea17a5280e529b82750da15f31f3d48b7da04
- Added a few methods to expose the fields e5093a2df2aae770b543fcd1bd7b4083b007d13a  &  e5093a2df2aae770b543fcd1bd7b4083b007d13a
- fix code that broke due to the move.

Also I've started to switch `VaultSync` over to `Handle` [hraesvel/impl_handle_for_vault_sync](https://github.com/Hraesvel/ockam/compare/hraesvel/transpose_handle...Hraesvel:hraesvel/impl_handle_for_vault_sync?expand=1).

- convert `VaultSync` 548e3b21e6c27996a757361077fa375a05f98a78, as for label the methods to `depricated & allow unused` I figured that was the best way to bother appease the `#[deny(...)]` and not break code. 
  -  I actually commented `deprecated` attrs out in a later commit. would like your input. Eventually, once all the functions are converted these will be labeled as unused. 
- convert `hasher.rs` to use `call()` methods 4a39c39fc0a31d3348c133807bb500101bc19fa9
- remainder is a bunch of temporary fixes.

want to talk about the conversion that was done to `hasher.rs` I found 2 variations, the difference is minor but it really comes down to use or not use turbo fishing.
[turbo fish](https://github.com/Hraesvel/ockam/blob/4a39c39fc0a31d3348c133807bb500101bc19fa9/implementations/rust/ockam/ockam_vault_sync_core/src/vault_sync/hasher.rs#L8)
[define variable types](https://github.com/Hraesvel/ockam/blob/4a39c39fc0a31d3348c133807bb500101bc19fa9/implementations/rust/ockam/ockam_vault_sync_core/src/vault_sync/hasher.rs#L21)

I'm leaning towards the turbo-fish. Though the main problem is that `ResultMessage` has to be converted with `into` to be useable. It's kind of a gotchya, I found this confusing at first when my tests were first failing.

Of course, I wouldn't mind someone weighing in if they can clean this up.
