### ISSUE TITLE
CI - Github action that turns any compiler warnings into Github issues.

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#1931]

**Comment by deepto98** [comment]
@mrinalwadhwa  I'd like to work on this issue, can you please assign it to me? Also can you suggest how I can get started on this, I'm aware of github actions, but need some help regarding how warnings can be handled as events

**Comment by metaclips** [comment]
@mrinalwadhwa @deepto98 we could run [`RUSTFLAGS="-D warnings" cargo check`](https://rust-unofficial.github.io/patterns/anti_patterns/deny-warnings.html) only on `develop branch` and then if the command fails, we create an issue with the logs. What do you all think?.
Why I suggest the CI should run only on develop is that originally, our CI fails on `#![deny()]` errors so if `warnings` is omitted, we get to catch the errors after merge. Also, we don't want to be flooded with issues due to omitted `warnings`.

**Comment by thomcc** [comment]
So, I'm not sure what this means really. I kind of don't think we should plan on merging code into develop before `cargo check`/`cargo clippy` are clean and I also don't think we should assume `#[allow(...)]` is always a TODO — it's often because the lint doesn't apply for whatever reason.

In fact, for clippy lints, they're developed under the assumption that you *will* use allow (and that that's good — it serves as "documentation" that "yes, I know this looks odd, it's intentional", and so it's not really a bug if the lints have false positives — anything that *might* cause issues should be pointed out.

OTOH for `cargo check` lints those have very few false positives, and I'd be okay with filing issues on any commented-out item in #![deny] at the crate root.

(Also, Note that at the moment, there are issues with our detection of warnings, which are fixed in #1816)

**Comment by mrinalwadhwa** [comment]
Closing, its too old, we can revisit if we feel the need again.
