### ISSUE TITLE
Use of msg.body() in handle_message() throws error

### ISSUE THREAD

**Issue by ade5h** [build-trust/ockam#2444]
When I tried running `cargo run` on [example project](https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_examples/example_projects/okta/management_app), I was getting the following error:

![ockam_issue](https://user-images.githubusercontent.com/17948555/149938098-29d90f45-f6b5-417c-8d73-4d1f79d9cbf9.png)

This is the msg.body() in handle_messgae() that throws the error:
https://github.com/ockam-network/ockam/blob/25ab1c6a8a09f8fdc177c41b6c40a0a6d89b1be3/implementations/rust/ockam/ockam/src/stream/consumer.rs#L222

This error seems to arise is due to the way the ownership is handled in body() method: 
https://github.com/ockam-network/ockam/blob/25ab1c6a8a09f8fdc177c41b6c40a0a6d89b1be3/implementations/rust/ockam/ockam_core/src/message.rs#L153-L156 
Should we implement the Copy trait for Routed or is there any other way to fix this?

**Comment by etorreborre** [comment]
@ade5h thanks for reporting this. I don't know exactly what went wrong at the time since we don't have this 'example project' in our code base any more. That being said the `consumer.rs` file is always compiled with the rest so there shouldn't be any compilation issue. Please re-open this issue if you still have some problems with examples and we will track it down.
