### ISSUE TITLE
Context struct should implement Debug

### ISSUE THREAD

**Issue by ashleygwilliams** [build-trust/ockam#2576]
In attempting to debug a small program I'm writing (as a beginner to Ockam), I wanted to print out the `Context` struct and ran into the fact that it does not implement debug.

```
error[E0277]: `ockam::Context` doesn't implement `Debug`
  --> src/tunnel/mod.rs:16:45
   |
16 |     println!("node started, context: {:?}", &ctx);
   |                                             ^^^^ `ockam::Context` cannot be formatted using `{:?}` because it doesn't implement `Debug`
   |
   = help: the trait `Debug` is not implemented for `ockam::Context`
   = note: this error originates in the macro `$crate::format_args_nl` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by spacekookie** [comment]
There's a bunch of stuff in there that we probably shouldn't dump in their entirety (like message buffers), but yea it'd be good to have access to _most_ of the fields

**Comment by Jackbaude** [comment]
I can maybe take this issue. Is this the correct file? https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_node/src/context.rs

**Comment by Jackbaude** [comment]
> Yep, that's right, and the issue is yours.

Few questions:
1) Why can we not release some information - such as message buffers mentioned by @spacekookie. What fields can we give out?
```
pub struct Context {
    address: AddressSet,
    sender: Sender<NodeMessage>,
    rt: Arc<Runtime>,
    mailbox: Receiver<RelayMessage>,
    access_control: Box<dyn AccessControl>,
}
```
2) If I already have an outstanding PR on the `develop`, do I need to make a new feature/bug branch and PR that branch?

**Comment by thomcc** [comment]
1. I honestly would just show the address, but perhaps someone else thinks the other fields should be shown.
2. I've merged your PR, but in general it's typical to make a new branch off of develop for each PR you have.

**Comment by thomcc** [comment]
@ashleygwilliams, what were you hoping to have displayed when you debug-logged the Context?

**Comment by ashleygwilliams** [comment]
I was definitely looking for the address- the other stuff I am not terribly familiar with so it's hard for me to weigh in on its usevalue. I do know I would probably be surprised if Debug *didn't* print any elements of the struct that I as a user somehow "set" (if that makes any sense).

I'd probably default to trying to show all of it unless it was prohibitive for some reason (length, etc) and very clearly unhelpful.

**Comment by thomcc** [comment]
Some of the contents could be sensitive data that has been serialized, so I'd hesitate about printing everything. That's my main concern, more then length[^1]

[^1]: Although length is a concern when they're byte arrays, since printing them is... kinda annoying; it will just come through as `[111, 99, 107, 97, 109, ...]` rather than something like `b"ockam"...`.

Although, I guess maybe we no longer send private keys and the like through messages, and only go through Secrets (e.g. integer ids), so maybe it's fine.

**Comment by thomcc** [comment]
@Jackbaude I think you should print out the AddressSet, and then anything else that implements Debug already, and we'll adjust if it has an issue (I think probably the issue about secrets is likely a bug if we ever do this now anyway).

Please use this API on the formatter, since you need to manually impl core::fmt::Debug, I think: https://doc.rust-lang.org/beta/std/fmt/struct.Formatter.html#method.debug_struct

**Comment by ashleygwilliams** [comment]
If it is at all helpful, when I poked at this this morning it seemed everything impl'd Debug except for AccessControl.

**Comment by spacekookie** [comment]
> > Yep, that's right, and the issue is yours.
> 
> Few questions:
> 
>     1. Why can we not release some information - such as message buffers mentioned by @spacekookie. What fields can we give out?

I think mostly the address is relevant. I actually don't know what the `Debug` implementation for the tokio Receiver prints out. If it gives us some metadata like how many messages are in the channel, then we can include it. If it's anything more spammy then we should skip it.

The rest is really irrelevant.

**Comment by Jackbaude** [comment]
Submitted a PR, although I think I messed up branching

**Comment by etorreborre** [comment]
This issue was implemented as part of https://github.com/build-trust/ockam/pull/4301
