### ISSUE TITLE
Consider using KeyId or other representation for Secret instead of integer

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#2664]
The problem is that integer Secret gets incremented each time new secret is created (which can happen very often and very many times). Some part of the secrets (mostly ephemeral) will eventually get unused (hopefully, destroyed as well), however used integer values are not reusable, which may make vault fail sooner or later even with u32 as an integer backend.

**Comment by thomcc** [comment]
I think another reason to do this would be that it avoids any risk of collisions.

**Comment by SanjoDeundiak** [comment]
@thomcc what do you mean? Incremented integers do not collide

**Comment by thomcc** [comment]
Two different vaults. We have `VaultError::SecretFromAnotherVault` for this, but a lot of the time it would just silently work, if the vault is in both.

It's not that likely of a case, can happen and is hard to track down when it does. For a short period of time, we had it in Firefox due to improper dynamic library handling on Android -- it's why https://docs.rs/ffi-support/latest/ffi_support/handle_map/struct.Handle.html indicates which map it comes from and that value is even randomized across different loads of the same DLL.

But that's probably overkill for us. Using a key id (or similar) is enough for us, probably better even.

**Comment by thomcc** [comment]
I think that's better than returning a secret from the wrong vault (e.g. succeeding incorrectly). Not that that's that likely, since I doubt many use cases have many vaults.
