### ISSUE TITLE
Failing test in websocket transport

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#2720]
This test fails occasionally:
https://github.com/build-trust/ockam/runs/6336949886?check_suite_focus=true

**Comment by mrinalwadhwa** [comment]
Another failure
https://github.com/build-trust/ockam/runs/6337783599?check_suite_focus=true#step:9:1560

**Comment by adrianbenavides** [comment]
Seems like a port collision. I'll look into that ASAP, I'm thinking about creating a `PortPool`... I'll get back with more details once a dig into it.

**Comment by adrianbenavides** [comment]
I can confirm is a port collision. The same happens with any test that connects to a port. I can reproduce this error by running a single test serially (i.e. running `cargo test -p ockam_transport_websocket --test send_receive` in a loop), so it's not that two different tests are trying to connect to the same port in parallel, but rather that some resources are not being freed in the OS.

In short, if we have two tests running serially connecting to the same port but they run very fast one after the other, it will fail because the OS couldn't release the socket.
