### ISSUE TITLE
Remove CI duplication

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#2953]
The CI jobs in these two workflows

https://github.com/build-trust/ockam/blob/develop/.github/workflows/documentation.yml
https://github.com/build-trust/ockam/blob/develop/.github/workflows/rust.yml

have some duplication around testing examples, we should figure out the duplicate parts and remove them

**Comment by neil2468** [comment]
Can I take this on, please?

**Comment by neil2468** [comment]
I was thinking of modifying the root `Cargo.toml` so that the workspace has the main ockam packages as default members.

That would mean that code and tests in `examples/rust/*` and `tools/docs/*` would no longer be built by default by a `cargo build` or `cargo test` command. But, I imagine, that is what developers would want most of the time anyway. 

Then in gradle and CI, the `examples/rust/*` and `tools/docs/*` stuff could be built and tested by specifically specifying something like `cargo build -p <package_1> -p <package_2>`. 

What do you think? Would that be okay? 🤔

Or maybe, we prefer to keep things as-is, in which case the only value `documentation.yml` is currently adding is checking if the code snippets in `README.md` files match the original source code. The `run_examples.sh` and `run_kafka_example.sh` can be removed as the same tests are now done by rust integration tests inside the `examples/rust/*` packages.

**Comment by mrinalwadhwa** [comment]
> Can I take this on, please?

Of course, thank you

I'll think about the workspace change. But in the meantime removing the following would be great 👍 
> The run_examples.sh and run_kafka_example.sh can be removed as the same tests are now done by rust integration tests inside the examples/rust/* packages.
