### ISSUE TITLE
Router doesn't check if address is already taken while starting Worker/Processor

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#3061]

**Comment by mrinalwadhwa** [comment]
@pro465 since you were looking for an issue to pick up today and you recently spent some time with the `ockam_node` crate. This issue may be a good one for you to take on. What do you think?

The router being discussed is here https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_node/src/router

@SanjoDeundiak could you add a small failing test snippet?

**Comment by pro465** [comment]
@mrinalwadhwa well i guess i got busy before you asked me to lol! but my other PR should not take much time, so i will be able to work in this in.. i guess 1-2 hours?

**Comment by mrinalwadhwa** [comment]
Awesome, we're not in a rush. Whenever you have time.

**Comment by pro465** [comment]
question: how do we check if the address already exists? do we have to just check if it exists in `router.map.{internal, addr_map}`? or do we have to send requests?

**Comment by SanjoDeundiak** [comment]
@pro465 I think you should check the Router's map and send an error back

**Comment by pro465** [comment]
@SanjoDeundiak should the error be `NodeError::Address(primary_addr).already_exists()`?

**Comment by pro465** [comment]
#3126 should fix this 🎉 , although the tests are not running as of typing this, I'm confident they will pass, because any test should not depend on the overwriting to pass.
