### ISSUE TITLE
Lint shell scripts with shfmt

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3588]
Lint all ockam shell script with [shfmt](https://github.com/mvdan/sh) in CI. Requires #3587

**Comment by elpiel** [comment]
I want to pick up this one.

**Comment by mrinalwadhwa** [comment]
@elpiel awesome, all yours. Let us know if you have any questions.

**Comment by elpiel** [comment]
Great, thanks!

- Should I add a config file? (I guess in `tools/shfmt`)
- Are there files that should be excluded?
- I see that #3587 has added this linter in a Dockerfile, however, there is already a Docker image - https://hub.docker.com/r/mvdan/shfmt and I'm not sure where this Dockerfile image from #3587 is used in order to call `shfmt`
- Any particular workflow I should add `shfmt` to or create a separate one like `semgrep`?

**Comment by metaclips** [comment]
Hello @elpiel 😁.
- Yes, please do. Thanks.
-  We want to lint all shell script. It's fine if scripts fail `shfmt` format, we will fix failing script in consecutive PRs
- Binary is installed in our latest builder package https://github.com/build-trust/ockam-artifacts/pkgs/container/ockam-builder with SHA `sha256:2b53a00493005871ab31c3e1e4e979fa76e21cd20bbc96773f25bd6b73d2a068`
- We should have a separate workflow for script format

**Comment by elpiel** [comment]
- There is a `shfmt` docker image and we can remove the install script from the builder.
- There isn't a separate file for config, only editorconfig option
- will add a PR with the builder for now, but if you decide to use the official docker image, we can change that.

**Comment by mrinalwadhwa** [comment]
@elpiel great, using the official docker image makes sense. Let's do that 👍

**Comment by elpiel** [comment]
> @elpiel great, using the official docker image makes sense. Let's do that +1

Done! And I hope you have a good rest after this long day @mrinalwadhwa :D
