### ISSUE TITLE
CHANGELOGs appear to contain duplicated lines

### ISSUE THREAD

**Issue by neil2468** [build-trust/ockam#3840]
At first glance, it looks like `CHANGELOG.md` files contain duplicate comments.

For example, below is a snippet from `ockam_vault/CHANGELOG.md` where it looks like lines newer releases are being copied from previous releases (e.g. `Switch to arch agnostic integers for secret length`).

```
## 0.67.0 - 2022-11-08

### Changed

- Switch to arch agnostic integers for secret length
- Codespell implementations/rust/
- Complete hkdf version update
- Updated dependencies

### Removed

- Remove bls support

## 0.66.0 - 2022-09-21

### Changed

- Switch to arch agnostic integers for secret length
- Updated dependencies

## 0.65.0 - 2022-09-09

### Changed

- Switch to arch agnostic integers for secret length
- Updated dependencies
```

This appears to happen in multiple `CHANGELOG.md` files, for example in `ockam_command` and `ockam_core`.

**Comment by mrinalwadhwa** [comment]
@neil2468 Thank you for reporting this.

**Comment by metaclips** [comment]
Thanks @neil2468. 
Our tags after `ockam_v0.63.0` diverge from `develop` branch due to `Mergify` changing commit SHA after PRs are merged, this causes git to assume our last release tag was `ockam_v0.63.0 ` from develop (running `git describe --tags --abbrev=0`).  I have added a workflow that updates commit SHA to that created by Mergify.
