### ISSUE TITLE
Add CLI command to list identities

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3932]
Add a new command to list the available identities. For each identity, show the same information as the `identity show` command.

A new `list` method must be implemented for IdentitiesState, similar to the NodesState's list method.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by ebrightfield** [comment]
Started poking around on this one, ran into a question.
https://github.com/build-trust/ockam/compare/develop...ebrightfield:ockam:feature/cli_identity_list?expand=1

Edit: Seeing other closely related GitHub issues clarified some things for me. Still one question, though.

In order to print the identity, it seems necessary to convert from `IdentityState` to an `Identity<Vault>`, which requires doing something like:
```
let identity = identity_state.config.get(&ctx, &vault).await?;
```
Which vault should I be acquiring and passing in?

Edit2: This one?
```
    let vault = opts.state.nodes.default()?.config.vault().await?;
```
Edit3: Actually, bats tests are leading me to believe it's this one? (`cmd.name` is the new way instead of using `NodeOpts`, re: a related issue to this one)
```
    let node = opts.state.nodes.get(&cmd.name)?;
    let identity = node.config.identity(&ctx).await?;
```

**Comment by adrianbenavides** [comment]
Hey @ebrightfield! Yeah, right now we don't want to couple identities to vaults, so there is no way to know what vault should be used to build the identity (other than brute force). So, to get the first version of this command, which should cover the most common use case, let's use the default vault to try to load all the identities, and skip those that fail to be loaded.

Also, note that identities are also independent of nodes, so, to get the list of the available identities, you must read them directly from the `identities` directory.

Take a look at the [cli_state](https://github.com/build-trust/ockam/blob/b9861eaaf1de7a73117c9cae18ede8546767d0bb/implementations/rust/ockam/ockam_api/src/cli_state.rs)  module (and more specifically, to the `IdentitiesState` struct) and of course, ask any question you have!
