### ISSUE TITLE
Encrypt/decrypt API for secure channel worker

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#3962]
Currently secure channels can only forward the messages they encrypt or decrypt.

This limits secure channels to scenarios where message needs to be sent to the other end using established session routes.

Sometimes messaging systems need to use other mechanism to deliver messages (e.g. messaging brokers) but still need to encrypt messages to provide security guarantees of the secure channel.

To facilitate that, secure channel worker API can be extended to provide the following:
- Encrypt arbitrary data using secure channel state (keys, nonce etc)
- Decrypt and verify encrypted data origin
- Fetch local and remote identity_ids

**Comment by SanjoDeundiak** [comment]
I've been thinking about this Secure Channel feature request, and realized it's not so easy to do, the problem is that on the responder side all the information you get after starting a listener - is when someone sends a message through a secure channel to one of your workers, and in this case all you know - is the encryptor address. Therefore, it's not clear how having that, responder could access this new API, since it doesn't even know an address for it. The possible solution to that is creating a new TransportType for Secure Channels, which implies having a SecureChannelRouter that contains a registry of existing channels.

### This is how roughly creating a channel looks like now
#### Bob
```rs
let storage = InMemoryStorage::new();

let bob = Identity::create(&ctx, &vault).await?;

bob.create_secure_channel_listener("bob_listener", TrustEveryonePolicy, &storage).await?;

let msg = ctx.receive::<String>().await?;
let return_route = msg.return_route();
ctx.send(msg.body(), return_route).await?;
```

#### Alice
```rs
let storage = InMemoryStorage::new();

let alice = Identity::create(&ctx, &vault).await?;

let channel = alice.create_secure_channel(route!["bob_listener"], TrustEveryonePolicy, &storage).await?;

let reply = ctx.send_and_receive(route![channel, "app"]).await?;
```

### This is how it can look like after

#### Bob
```rs
let storage = InMemoryStorage::new();

let secure = SecureChannelTransport::create(&ctx, &storage).await?;

let bob = Identity::create(&ctx, &vault).await?;

secure.create_listener("bob_listener", &bob, TrustEveryonePolicy).await?;

let msg = ctx.receive::<String>().await?;
let return_route = msg.return_route();
ctx.send(msg.body(), return_route).await?;
```

#### Alice
```rs
let storage = InMemoryStorage::new();

let secure = SecureChannelTransport::create(&ctx, &storage).await?;

let alice = Identity::create(&ctx, &vault).await?;

let channel = secure.create_channel(route!["bob_listener"], TrustEveryonePolicy).await?;

let reply = ctx.send_and_receive(route![channel, "echoer"]).await?;
```

#### Bob
```rs
// Now available
let list = secure.get_channel_list().await?;

// Also possible
let channel_address = return_route.next()?; // Secure channel can also be found by new Transport Type constant - `Secure`
let api_address = secure.get_api_address(&channel_address).await?;
// Use api_address to access encryption/decryption directly

// Potentially, very useful for Outgoing Access Control
let alice_id = secure.get_participant_id(&channel_address).await?;
```

#### Also possible to implement after that change:
```rs
// Resolved like TCP address: if there is an existent secure channel with Bob - message will be sent there
ctx.send(route![(Secure, {bob_identifier}), "app"], "Hello").await?;
```

This is a huge change, also I suspect merging IdentitySecureChannel and SecureChannel can be required to achieve that, which will require a change on elixir side as well.

Thoughts?

**Comment by hairyhum** [comment]
Could we just have a worker listening for some "init" message from the SC responder and learn the address this way?
We do anticipate some setup happening between initiator application and responder application.

**Comment by SanjoDeundiak** [comment]
### Suggested change:
1. Introduce `SecureChannelRegistry` that would contain information about all secure channels
2. Allowing to look for a secure channel information by a given encryptor address
3. Implement API address for encryptor and decryptor workers that allows to encrypt/decrypt data without sending it

**Comment by SanjoDeundiak** [comment]
There is one implementation detail I would like to discuss: given we have outer Identity SecureChannel and inner regular SecureChannel, I'll need to implement API address for both of them. The alternative would be to merge Identity SecureChannel and regular SecureChannel (so that there is one encryptor and one decryptor worker per channel, instead of 2&2 right now, which AFAIK we already wanted to do). This would simplify my work, but probably require elixir side to do the same change. Thoughts?
