### ISSUE TITLE
Elixir: Support for unix domain socket transport

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#4042]
Unix domain socket transport can be used to communicate between nodes locally: https://github.com/build-trust/ockam/pull/3927

Currently Elixir nodes use sidecar Rust nodes for identity management and it would be useful if those sidecar nodes did not need to expose a TCP listener.

**Comment by aecepoglu** [comment]
I want to do this ticket.

Commenting w/ my understanding of the issue and the solution and posing a question. Let me know if they make sense.

We should extend the TCP interface to accept file based sockets (since they differ from the port-bound sockets in address only) rather than create a new transport.

`Ockam.Transport.TCP.Listener` will accept a "(file)path": `[port: 4000]` or `[socket_path: "/tmp/my-socket.sock"]` .

This allows us to supply `[port: 4000, socket_path: "/tmp/my-socket.sock"]` as well. How should I address this?

* If `Listener.start_link(options)` was replaced with `Listener.start_link({:socket, options})` and `Listener.start_link({:port, options})` there would be no ambiguity.
* We can prioritise one option over the other and let both of them be defined

**Comment by nazmulidris** [comment]
@aecepoglu That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by aecepoglu** [comment]
OK, summing the questions here:

1. How does this relate to https://github.com/build-trust/ockam/pull/4220 ?
2. Are we looking for a new Transport or a new address? The PR linked above creates a new Transport. Besides the address everything else should be the same so I am not sure we want to create a new Transport. The diff is

    ```elixir
    shared_opts = [...]
    {:ok, socket1} = :gen_tcp.listen(0,       [ifaddr: {:local, "/path/to/socket"}] ++ shared_opts)
    {:ok, socket2} = :gen_tcp.listen(4040,                                             shared_opts)
    ```
    
    Or for Ranch it seems to be
    ```erlang
    {ok, _} = ranch:start_listener(tcp_echo,
      ranch_tcp, #{socket_opts => [
          {ip, {local, "/tmp/ranch_echo.sock"}},
          {port, 0}
      ]}, echo_protocol, []
    ).
    {ok, _} = ranch:start_listener(tcp_echo,
      ranch_tcp, #{socket_opts => [{port, 4040}]},
      echo_protocol, []
    ).
    ```
     If we want to have a `Transport.UDS.*`, wouldn't `Transport.TCP.Handler` and `Transport.UDS.Handler` be identical?

3. If we're happy with using the TCP listener and client for UDS, how do we initialise them without ambiguity. What would `TCP.Listener.start_link([port: 4000, uds_path: "/tmp/my-socket.sock"])` mean and can we do `Listener.start_link({:uds, options})` and `Listener.start_link({:port, options})` instead?

**Comment by polvorin** [comment]
hi @aecepoglu  thanks for your interest and sorry for the confusion,  this is an old ticket that should had been closed already.

Elixir code used to rely on a  rust node running as sidecar, to perform certain operations (mainly cryptographic primitives related to establishing secure channels,  verifying credentials, and so on).    The communication between elixir and the rust sidecar was through TCP socket.  This ticket was about making that communication happens over unix domain socket instead.

*BUT*  these primitives are accessed using a standard NIF approach now,   we don't run a standalone rust process (sidecar) alongside elixir anymore. 

Closing this ticket, and again, sorry for the confusion

**Comment by polvorin** [comment]
@aecepoglu  actually,   the work to have a unix domain transport was never finished,  so that's still open and I encourage if you want to take that one! https://github.com/build-trust/ockam/issues/6755.

On your questions,  we are on the same page 😄  :
2.) Are we looking for a new Transport or a new address? 
* New transport,  lets not introduce a "unix-domain-address-type". 
*  Transport will be created explicitly (by creating a listener,  or a client)
* Agree about likely possible to reuse existing implementation 👍  .  But if used as-is lets rename it to StreamSocket or something similar

3.)  If we're happy with using the TCP listener and client for UDS, how do we initialise them without ambiguity. 
I personally would prefer  a UDS module that delegate the listener and connect calls to an underling base module,  and a TCP one doing the same.    The base module can then accept the parameters as you proposed,  and likely _not_ be exposed to client code.

**Comment by aecepoglu** [comment]
I'll be looking into 1-2 other tickets before I return to this one. If the ticket _is_ still open should we remove the "closed" status then?

**Comment by nazmulidris** [comment]
@aecepoglu Thanks for taking a look at other tickets. In the future if you want to return to this ticket, you can just start working on this new one instead (to allow you to continue your work): https://github.com/build-trust/ockam/issues/6755 (not this one which will remain closed)
