### ISSUE TITLE
Concurrent tests and CLI state

### ISSUE THREAD

**Issue by davide-baldo** [build-trust/ockam#4345]
**Describe the bug**
In cargo, tests are executed in parallel in the same process.
Every test expects to have isolation from other tests, but every test using `okam_api` actually **shares `OCKAM_HOME` across test**, which causes random failures.
Even if tests set `OCKAM_HOME` this causes even more issues since tests will be competing for the same global state.

**To Reproduce**
Randomly reproduce it when running tests with a high amount of threads.
So far has been reproduced by @SanjoDeundiak.

**Solution**
The obvious solution is to avoid the usage of `OCKAM_HOME`  as a global state and make it explicit in every test context, however,  `OCKAM_HOME` is **always implicit** through `CliState::dir()` or in a more indirect way.
Almost every usage of `ockam_api` needs to add the `ockam_home` in the context to pass it along.
To further complicate things, some types are created using `Default::default()` but now they actually require `ockam_home`.

**Comment by adrianbenavides** [comment]
Yeah, this one has been around for quite a while. Here is a brief summary about the shared/global CLI data:

- Some months ago, there was a considerable amount of shared data between nodes. Back then I tried a couple of ideas to write CLI tests isolating them at https://github.com/build-trust/ockam/pull/3786, but it was just impossible for the reasons you described
- More recently, I tried at https://github.com/build-trust/ockam/pull/4192 to remove the last remnant of this global state, the now-called `config.json` file, which contains the lookup information about orchestrator spaces/projects. We couldn't merge that PR because it was interfering with the priority tasks at the moment

Now, regarding the proposed solution, that would be a quick win for local-only tests.

**Comment by davide-baldo** [comment]
> Now, regarding the proposed solution, that would be a quick win for local-only tests.

Unfortunately, it wouldn't be `quick`, there are hundreds of small changes.
I'll take a look at https://github.com/build-trust/ockam/pull/4192 then!

**Comment by adrianbenavides** [comment]
> Unfortunately, it wouldn't be `quick`, there are hundreds of small changes. I'll take a look at #4192 then!

Oh, I see, I guess you are talking about https://github.com/build-trust/ockam/pull/4338?

I think the problem about using OCKAM_HOME implicitly at CliState will still be there though. I can try to fix it without having to modify too much of the production code. I'll get back to you as soon as I can.

**Comment by davide-baldo** [comment]
> Oh, I see, I guess you are talking about https://github.com/build-trust/ockam/pull/4338?

Yes! that is the PR I tried to put up to fix the issue, but it doesn't work without reducing  `CliState::ockam_home_from_environment()` to 1 usage (direct and indirect), but trying to do so causes an avalanche effect
