### ISSUE TITLE
`ockam secure-channel-listener list --node n1` is inconsistent

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#4973]
### Observed behavior

`ockam secure-channel-listener list` uses ` --node` as an optional flag while all the other commands (`create/delete/show`) for `ockam secure-channel-listener` use `--at`.

### Steps to reproduce

`ockam secure-channel-listener list --node n1`

### Expected behavior

`ockam secure-channel-listener list --at n1` should be used instead

### Ockam Version

0.87.0

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by leafoliage** [comment]
@etorreborre Can I take this?

**Comment by mrinalwadhwa** [comment]
@leafoliage of course, let us know if you have any questions as you explore.

**Comment by leafoliage** [comment]
Hi. Where can I find the built binary file? I thought it's supposed to be in `/target/release`, and I've tried `cargo build`, but I can't find the binary in `/target/release`. (I've also tried `make build`, but it failed in the typescript part)

**Comment by etorreborre** [comment]
A simple `cargo build` should put the binary in `/target/debug` (and `cargo build --release` creates an optimised `release` executable in `target/release`)

**Comment by leafoliage** [comment]
It seems that there is no existing examples or tests for `secure-channel-listener list`?

**Comment by davide-baldo** [comment]
We have the [documentation example](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/secure_channel/listener/static/list/after_long_help.txt) 

We don't have tests for each command since they are too much of a moving target, we have only tests [for use cases](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/tests/bats), but there is no usage of `secure-channel-listener list` there.
