### ISSUE TITLE
`tcp-connection show` command should iter all the available nodes to find the requested ID

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4976]
### Current behavior

The [`tcp-connection show`](https://github.com/build-trust/ockam/blob/1b67b2166b873e450999443b5e9823b1868705d3/implementations/rust/ockam/ockam_command/src/tcp/connection/show.rs) expects a tcp-connection ID that is used to send a query to a node (either the default node or the one specified with the `--node` argument).

### Desired behavior

From the user perspective, I'd like to let the CLI fetch the given tcp-connection from the entire system (i.e. all the available nodes), so I don't have to try every possible node.

We need to refactor the command so that:
- it doesn't rely on a specific node (the `--node` argument is removed)
- it tries to look for the tcp-transport ID across all the available nodes
- it returns the node where it was found as part of the output
- it returns a "not found" error if it couldn't find it in any of the nodes

**Comment by etorreborre** [comment]
I would suggest to extend this issue with:

 - make the connection id optional in tcp-connection delete and delete all the connections coming from a given node if `--from` is specified

And maybe improve the usefulness of the `ockam tcp-connection list` command:

 - add a `from` field to the table returned by list when no `--node` is specified (and maybe rename the `--node` option to `--from` to be even more consistent) 
 - remove the `Transport Type` column since we already know that we are listing TCP connections
 - consider removing the `Mode` column
 - write `to` instead of `Socket Address` (to better relate it to the `ockam tcp-connection create` action)
 - consider removing the `Worker` column

**Comment by SanjoDeundiak** [comment]
This is heavily changed in https://github.com/build-trust/ockam/pull/4670 as it was required for my work. There is no Transport ID, and the outputs are improved.
Also I don't think we should avoid specifying a node argument, unless there is only one node on the system

**Comment by loghijiaha** [comment]
Would like to give it a shot? If nobody is working on this?

**Comment by adrianbenavides** [comment]
We still need to decide what to do with this one regarding whether to remove the `--at` argument or not. I'll let you know as soon as I have updates on this!

**Comment by adrianbenavides** [comment]
Closing this for now.
