### ISSUE TITLE
Please do not spam other GitHub users via email

### ISSUE THREAD

**Issue by mritzmann** [build-trust/ockam#4995]
### Observed behavior

On 21. May 2023, I received the following email from Ockam:

<details><summary>Email</summary>

> Hi,
> 
> I want to open with: I'm not a sales person! I've recently joined Ockam.io, a [popular open source project](https://github.com/build-trust/ockam) that helps developers build more secure systems. I'm hoping your expertise could provide some input on the future direction of our project.
> 
> Would I be able to grab 20 mins of your time for a call? I promise to keep it short & sweet and be respectful of your time and generosity.
> 
> Could I setup a short call?
> 
> --
> Glenn
> Director of Product @ Ockam.io
>  [build-trust/ockam](https://github.com/build-trust/ockam) 
>  [@glenngillen](https://twitter.com/glenngillen) 
>  [/glenngillen](https://www.linkedin.com/in/glenngillen/) 
>  Want to chat? [Book a time directly in my calendar](https://calendly.com/ockam-glenn/ockam-product-chat) 
> 
> "One of the top 40 most popular and fastest growing OSS security projects on GitHub" per Open Source Security Index

</details>

On 24. May 2023, I received the following email from Ockam:

<details><summary>Email</summary>

> Hi,
> 
> Just following up on this incase it got lost in your inbox. I'm sure your expertise would be invaluable in terms of guiding our open source project.
> 
> Could we chat some time this week?
> 
> --
> Glenn
> Director of Product @ Ockam.io
>  [build-trust/ockam](https://github.com/build-trust/ockam) 
>  [@glenngillen](https://twitter.com/glenngillen) 
>  [/glenngillen](https://www.linkedin.com/in/glenngillen/) 
>  Want to chat? [Book a time directly in my calendar](https://calendly.com/ockam-glenn/ockam-product-chat)  
> 
> "One of the top 40 most popular and fastest growing OSS security projects on GitHub" per Open Source Security Index

</details>

To be clear:

* The email was sent to my email-address, which is used in my GitHub profile and in public git commits
* According to the header, it was sent with [Sendgrid](https://sendgrid.com/), which is why I assume that it was sent in bulk to various users
* I have reported the emails as spam to my email provider and Sendgrid
* I have never used Ockam nor do I know the company or the product
* I will never want to use Ockam for this reason either

I consider such email practices to be spam and unworthy of a reputable company and GitHub project, and also assume that using publicly visible email addresses on GitHub for such purposes also violates the GitHub TOS. It is also a pretty bad practice to send such emails and shows bad morals. Please do not spam other GitHub users via email.

### Steps to reproduce

--

### Expected behavior

Please do not spam other GitHub users via email.

### Ockam Version

--

**Comment by glenngillen** [comment]
Hey @mritzmann, I'm the person that sent you that email. Let me say upfront that I apologise, and I've ceased sending any further emails to anyone.

You're correct that I have reached out to people based on the email address they have on their GitHub profile. I've strived to be deliberate and considered in the people I reach out to so that it's not a scattershot approach and relevant to our shared interests. As I briefly imply in the email, the intention was to help get me more broader perspectives that could help our project (i.e., from outside the existing community we have). Intentions don't matter here though, as clearly I've breached your trust and that's not an outcome any of us wanted. I'll reflect on this with the team next week and we'll discuss other approaches to achieve what I set out to do. I appreciate the feedback and, again, apologies for over stepping.

**Comment by kjvdven** [comment]
Still sending spam.

Spam reported also with Sendgrid.

**Comment by glenngillen** [comment]
@kjvdven can you please forward me the email you received glenn@ockam.io

**Comment by glenngillen** [comment]
@kjvdven no need, I found the issue and disabled the email campaign in question. I'll delete it later today so it can't be turned on again. My apologies.

**Comment by glenngillen** [comment]
Those lists have now been permanently removed rather than just switched off, so this won't happen again. Once again, my apologies.
