### ISSUE TITLE
Allow a user to interrupt the enrollment process

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5241]
Please read the description of the [Ockam app](https://github.com/build-trust/ockam/issues/5228).

Currently if the interrupts the enrollment process, for example by closing the activation window, then the desktop application stays in waiting state forever. 

We should find a way for the user to stop current enrollment action and start a new one.

**Comment by mrinalwadhwa** [comment]
Instead of requiring the use to interrupt it. I think we should instead spin it off to the background and timeout if it doesn't complete in time. During this period the button should remain active and may get clicked again.

**Comment by etorreborre** [comment]
There is already a timeout (60s) but it would be nice to nice to be able to cancel the action, for example to focus on a different browser window, instead of having to wait for the whole duration.

**Comment by mrinalwadhwa** [comment]
I was imagining that we won't have to wait because the `Enroll...` button stays active.
So a user would close the old browser window, from their perspective the process is now cancelled. They would then click `Enroll...` without having to wait since it is still active.

We handle the fact that there are now two runs in the background.

**Comment by etorreborre** [comment]
This can now be done by simply letting the timeout expire or quitting the application and re-enrolling again.
