### ISSUE TITLE
Ockam CLI should gracefully handle invalid state when initializing

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#5633]
### Observed behavior

Currently, `ockam_command` expects its state to be valid, and if it's not - it panics [here](https://github.com/build-trust/ockam/blob/3c06be25cd02794016562af33d2e55f765142539/implementations/rust/ockam/ockam_command/src/lib.rs#L223)

### Steps to reproduce

1. Remove ockam state directory (usually it's `~/.ockam`)
2. Run `ockam identity create`
3. Go to `~/.ockam/identities/{ID}.json` file and mangle it (e.g., change the json key value from `identifier` to `id`)
4. Run `ockam reset --yes`

### Expected behavior

1. At least for `ockam reset` command, we should ignore this error and wipe the state so that the next command would start from scratch and succeed.
2. We should handle this error gracefully and return a proper error instead of panicking

**Comment by Qeyphen** [comment]
@SanjoDeundiak I'm thinking the new error  should be added [here](https://github.com/build-trust/ockam/blob/3c06be25cd02794016562af33d2e55f765142539/implementations/rust/ockam/ockam_command/src/error.rs#L11). What should be the name of the error ?

Or do  I  make use of an existing error (like [InternalError](https://github.com/build-trust/ockam/blob/3c06be25cd02794016562af33d2e55f765142539/implementations/rust/ockam/ockam_command/src/error.rs#L55)) or a [CliStateError](https://github.com/build-trust/ockam/blob/2513cc701aacc9ccb32c715b096aa7d093abd1bd/implementations/rust/ockam/ockam_api/src/cli_state.rs#L33)?

**Comment by seve-martinez** [comment]
Not sure if this fits in here (or should be its own issue), but I noticed this also happens if you run `ockam lease --token_id 1234` before a project has been initialized. However, since this is deeper into the callstack, it will actually hang since the panic happens within an async task, which doesn't shut down the program.

Specifically here:
https://github.com/build-trust/ockam/blob/3c06be25cd02794016562af33d2e55f765142539/implementations/rust/ockam/ockam_command/src/util/orchestrator_api.rs#L210

A crtl-C is required to return to the terminal prompt.

**Comment by etorreborre** [comment]
Hi @0xphen this error is more of a `CliStateError` since it concerns the persistence of data by the `ockam_api` crate. This is:

 - a `500` error
 - with a type like `IncorrectFileFormat` (so that it can be skipped by `ockam reset -y`)
 - and a help text saying that users need to reset their command line state by running `ockam reset -y` (if another command led to a broken state)

**Comment by DogPawHat** [comment]
Was thinking of taking this if it available.

**Comment by etorreborre** [comment]
Hi @DogPawHat, that's very kind of you. Let's check with @0xphen if they have started working towards this or not.

**Comment by davide-baldo** [comment]
@DogPawHat 

It seems like the issue can be taken! Are you still interested in this development?

**Comment by DogPawHat** [comment]
Yeah. It seems like I'd have to maybe separate out the directory and file parts of `CliState` apart, as you have a chicken and egg situation where you need a `CliState` to reset the `.ockam` directory, you can't get a `CliState` if you have an error, so you need to reset the directory...

Would appreciate advise and help on this.

**Comment by Qeyphen** [comment]
@davide-baldo @etorreborre  apologies for taking too long to respond (I haven't been available for the past 2 weeks). @DogPawHat  I'm glad you're working on this; here's what I have gained so far from this issue: 

The error originates when trying to initialize the [IdentitiesState](https://github.com/build-trust/ockam/blob/b7253f50ca9afa4d73583fa1380f5d4b6782a087/implementations/rust/ockam/ockam_api/src/cli_state/mod.rs#L133). It tries to [migrate](https://github.com/build-trust/ockam/blob/b7253f50ca9afa4d73583fa1380f5d4b6782a087/implementations/rust/ockam/ockam_api/src/cli_state/identities.rs#L247) the configuration and fails. But from looking through the code, the `ockam reset -y` command doesn't need or depend on the configuration being migrated; since it resets the configuration.

**Comment by DogPawHat** [comment]
Can we have this assigned to me if we're all agreed?

**Comment by DogPawHat** [comment]
@0xphen thanks for your write up, that mostly tracks with what I've seen in the code.

**Comment by davide-baldo** [comment]
Thanks to both of you, It's wonderful to see this community grow and collaborate ❤️

**Comment by DogPawHat** [comment]
Small update, I'm still hacking away at this. I was trying to separate `StateItemTrait` into separate state traits (a la [state pattern](https://turreta.com/blog/2019/12/09/how-to-use-state-design-pattern-in-rust/)), in that the pre-validation state had just the `path` of the file, while the validated state had the de serialized config, the idea being to defer the de-serialization to the transition method (implemented as `TryFrom`) so that we could still used the `delete` method on the unvalidated file. Unfortunately I was soon adding extra method called to everywhere that needed the Item `.config()`, which was most of the codebase that did need the validated state.

I've changed tack to attaching a struct to the error produced when serde fails to parse so that the error handling logic can call `.delete()` in case `ockam reset` is called. This should be achievable with less LOC and a smaller PR.

**Comment by DogPawHat** [comment]
Hi, @adrianbenavides, I've a PR in draft, but I think your PR at https://github.com/build-trust/ockam/pull/6071 has this issue solved now, although I think it resets with any command if `CliState` fails to initialize.

**Comment by adrianbenavides** [comment]
@DogPawHat yes, my fault. We had to push this forward as it was impacting our production builds. I didn't see this issue when I created that PR and I never updated it. 

I'm closing the issue, but let me know if I can help you with any other issue you might be interested in, we have a lot of new issues that we created for the Hacktoberfest.

Thank you so much for spending your time on this 🙏  I hope you can find another issue to contribute to Ockam!
