### ISSUE TITLE
Consider adding a Builder to NodeManager

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#5666]
Currently, [NodeManager](https://github.com/build-trust/ockam/blob/2513cc701aacc9ccb32c715b096aa7d093abd1bd/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L98) is a somewhat tangled, big module. It could use some refactoring.

A good place to start may be creating a convenient Builder to avoid using the `NodeManager::create` function that takes a lot of options. There are multiple ways to do it, so some design ideas would be very welcome.

**Comment by seve-martinez** [comment]
For this are you thinking of consolidating the `NodeManagerGeneralOptions`, `NodeManagerTrustOptions`, and the `NodeManagerTransportOptions` as well i.e., have the builder create a fully functioning `NodeManager` by including optionally chained methods that could also create these things?

Something like the [SecureChannelsBuilder](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_identity/src/secure_channels/secure_channels_builder.rs#L10)?

**Comment by SanjoDeundiak** [comment]
That would be a nice start @seve-martinez !

**Comment by seve-martinez** [comment]
I'd love to give this a shot. Please assign it to me 🚀

**Comment by seve-martinez** [comment]
@SanjoDeundiak hi I just have a clarifying question re: design.

Looking at [this creation call](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/create.rs#L314-L329) as an example, I foresee the API looking something like this:
```rust
let node_man = NodeManager::new(&ctx)
  // general config opts
  .node_name(node_name.as_ref())
  .skip_defaults(cmd.launch_config.is_some())
  .pre_trusted_identities(pre_trusted_identities)
  .cli_state(cli_state.clone())
  // transport opts
  .flow_control_id(listener.flow_control_id().clone())
  .tcp_transport(tcp.async_try_clone().await.into_diagnostic()?)
  // trust opts
  .trust_context(trust_context_config)
  .create()
  .await
  .into_diagnostic()?;
```

However, in the `create` method, some of these are _required_ to be present in order for a `NodeManager` to be created. An example is the [node_state](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L321) which must have a `CliState`.

In order to prevent misconfigurations, I wanted to use typestate, but that comes with challenges:

```rust
struct NotCreateable;
struct Createable;

struct NodeManagerBuilder<W> {
  // fields

impl<W> NodeManagerBuilder<W> {
 // things that aren't explicitly needed to construct a NodeManager
}

impl NodeManagerBuilder<NotCreateable> {
  // methods that return an intermediate builder, not ready for construction
}

impl NodeManagerBuilder<Createable> {
  pub fn create(self) -> NodeManager {
    // we can be sure that the necessary items to construct a NodeManager are present.
  }
}

``` 
The trick here is knowing _when_ an object is createable. A helper function could be provided under the `NodeManagerBuilder<NotCreateable>` type which could do this check:
```rust
pub fn validate(self) -> NodeManagerBuilder<Createable> {
  // some checks to ensure the items to build this thing are present
}
```
But because these checks would happen at runtime, it effectively negates the benefits of the typestate builder. you could still just as easily call only one of the methods, then `validate()` and it would compile.

A simpler may be to just validate the presence of the necessary attributes within the `create` method and return an error if something is missing:

```rust

fn create(self) -> Result<NodeManager> {

  // whatever is required for this to return a node manager
  match (self.x, self.y, self.z) {
     (Some(x), Some(y), Some(z)) => {} // create a node manager,
     _ => return err
  }

}

```

What do you think?

**Comment by etorreborre** [comment]
Hi @seve-martinez. Thanks a lot for starting to share useful thoughts on this subject.

I would actually like to put this on hold for now because I started doing some refactorings between `ockam_command` and `ockam_api` to simplify how we make calls inside a node ([here](https://github.com/build-trust/ockam/pull/5916) is a PR preparing the work). 

This is going to touch how we create and pass around a `NodeManager` so I'd rather not have too much friction there. I also want to see if we can start carving out some interfaces and implementations so that we don't have to pass around this ["God object"](https://en.wikipedia.org/wiki/God_object).

More importantly, you pointed out the question of the `CliState`. We think it needs to be revisited. We are now planning a big overhaul of the `CliState` to use a relational database for backend persistence instead of a tree of directories and files. This is going to have a major impact on how we create a node so we _will_ have to revisit this issue at this stage anyway.

Please stay tuned, I will post issues for which I will love to have contributions as soon as I get a little more clarity on the current refactoring. Thanks for your help!
