### ISSUE TITLE
Improve `ockam enroll` output when an identity is created and set as default

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#6538]
Messages displayed when we run `ockam reset --yes && ockam enroll` about creation of a new identity are repetitive and maybe confusing.

<img width="873" alt="Screenshot 2023-10-14 at 12 08 07 PM" src="https://github.com/build-trust/ockam/assets/159583/04455500-77a7-4f91-bc34-082ef1881ae9">

I'm running `v0.97.0` haven't had a chance to try the latest develop branch.

The source for the enroll command is here
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/enroll

**Comment by mrinalwadhwa** [comment]
Copying @nazmulidris and @adrianbenavides incase they have thoughts on how to improve.

**Comment by adrianbenavides** [comment]
The problem is happening in the `create_default_identity` function:

https://github.com/build-trust/ockam/blob/f423ec1451203e26a41c56e05119866dc68bb9ee/implementations/rust/ockam/ockam_command/src/identity/mod.rs#L80-L84

We need to stop calling the `CreateCommand::new()` command and create the identity manually, because the command is always going to print its output to stdout. The command's logic (the contents from [this block](https://github.com/build-trust/ockam/blob/ed8054ecd1ddcdfc945d08b7f9d516e299d9abc4/implementations/rust/ockam/ockam_command/src/identity/create.rs#L68)) that creates the identity should be extracted to its own function so that we can call it from both places:

Another solution would be to just delete the [ad-hoc logs](https://github.com/build-trust/ockam/blob/f423ec1451203e26a41c56e05119866dc68bb9ee/implementations/rust/ockam/ockam_command/src/identity/mod.rs#L93-L105) from `create_default_identity`.

@nazmulidris @mrinalwadhwa any preference on what section do you want to preserve?

![Screenshot 2023-10-15 at 07 01 22](https://github.com/build-trust/ockam/assets/12375782/1e30f69f-2b0c-4642-b86d-aa7713d98d88)

**Comment by Lumexralph** [comment]
@adrianbenavides @mrinalwadhwa Can I attempt this?

Can you please, help me with the steps to reproduce this?

**Comment by adrianbenavides** [comment]
Sure, all yours! You can reproduce it by running:

```
ockam reset -y
ockam enroll
```

The first thing that you'll see in the prompt will be the contents I posted in the image above. Let me know if you have any question.

**Comment by nazmulidris** [comment]
> @nazmulidris @mrinalwadhwa any preference on what section do you want to preserve?

@adrianbenavides I vote on this one
![image](https://github.com/build-trust/ockam/assets/2966499/7cddb57b-5f68-44b3-8fd8-678557653aff)

**Comment by Lumexralph** [comment]
@nazmulidris @adrianbenavides If we are going with the first option, I guess removing this [block statement](https://github.com/build-trust/ockam/blob/f423ec1451203e26a41c56e05119866dc68bb9ee/implementations/rust/ockam/ockam_command/src/identity/mod.rs#L93-L105) will achieve that or do you have another idea?

If I extract the function that creates the identity, I would still need to update the logs to conform with the picked format by @nazmulidris

**Comment by adrianbenavides** [comment]
> @nazmulidris @adrianbenavides If we are going with the first option, I guess removing this [block statement](https://github.com/build-trust/ockam/blob/f423ec1451203e26a41c56e05119866dc68bb9ee/implementations/rust/ockam/ockam_command/src/identity/mod.rs#L93-L105) will achieve that or do you have another idea?

That's right, you can start with that. Once you have a PR ready we can review it and check how it looks 👍

**Comment by Lumexralph** [comment]
> > @nazmulidris @adrianbenavides If we are going with the first option, I guess removing this [block statement](https://github.com/build-trust/ockam/blob/f423ec1451203e26a41c56e05119866dc68bb9ee/implementations/rust/ockam/ockam_command/src/identity/mod.rs#L93-L105) will achieve that or do you have another idea?
> 
> That's right, you can start with that. Once you have a PR ready we can review it and check how it looks 👍

@adrianbenavides the PR is up https://github.com/build-trust/ockam/pull/6632, you can check it out
